name: build-deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: echo "Hello App" > app.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Read file
        run: cat app.txt