name: timeout-demo

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - name: Sleep
        run: sleep 600

  second:
    runs-on: ubuntu-latest

    needs: first

    steps:
      - run: echo "Second Job"